In [20]:

import numpy as np
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import r2_score
df3=pd.read_csv("dataset/combined.csv",usecols=['product_category_name_english','price'])
df4 = pd.get_dummies(df3)
X = df4.drop('price',axis=1)
y= df4['price']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,random_state=0)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_log_error

lreg = LinearRegression()
lreg.fit(X_train, y_train)
pred_train = lreg.predict(X_train)
train_score = np.sqrt(mean_squared_log_error(y_train,pred_train))
pred_test = lreg.predict(X_test)
test_score = np.sqrt(mean_squared_log_error(y_test,pred_test))
print('Training score:', train_score)
print('Test score:', test_score)

Training score: 0.9473651925519065
Test score: 0.9513544775011784


In [21]:
train_results = pd.DataFrame({'Giá thực tế (Huấn luyện)': y_train, 'Dự đoán giá (Huấn luyện)': pred_train})
test_results = pd.DataFrame({'Giá thực tế (Kiểm tra)': y_test, 'Dự đoán giá (Kiểm tra)': pred_test})

# In kết quả
print("\nKết quả dự đoán và giá thực tế cho tập huấn luyện:")
print(train_results.head())

print("\nKết quả dự đoán và giá thực tế cho tập kiểm tra:")
print(test_results.head())



Kết quả dự đoán và giá thực tế cho tập huấn luyện:
        Giá thực tế (Huấn luyện)  Dự đoán giá (Huấn luyện)
106668                    110.32                130.833221
63486                     899.00                205.792175
63397                     103.00                116.592773
95376                      89.99                136.908295
26599                     165.50                115.950653

Kết quả dự đoán và giá thực tế cho tập kiểm tra:
       Giá thực tế (Kiểm tra)  Dự đoán giá (Kiểm tra)
70687                  109.90              113.620697
98955                   45.95               92.821320
38238                   39.20               91.370605
8807                   349.00              115.950653
35906                   69.00              151.442078


* dự đoán về giá sản phẩm

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
df=pd.read_csv('data.csv')
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['freight_value'] = pd.to_numeric(df['freight_value'], errors='coerce')
df['sale'] = df['price'] + df['freight_value']
features = ['price', 'freight_value', 'review_score']
target = 'order_status'

# Chọn các cột có mặt số
X =df[features]
y = df[target]

# Chuyển đổi các cột mục tiêu thành số
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Chia dữ liệu thành tập huấn luyện và tập kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Tiền xử lý dữ liệu (chuẩn hóa)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# Khởi tạo mô hình
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Huấn luyện mô hình
model.fit(X_train, y_train)

# Dự đoán trên tập kiểm tra
y_pred = model.predict(X_test)


# Chuyển đổi dự đoán về dạng văn bản (nếu cần)
y_pred_labels = label_encoder.inverse_transform(y_pred)

# Tạo DataFrame chứa các dự đoán
results = pd.DataFrame({
    'Actual': label_encoder.inverse_transform(y_test),
    'Predicted': y_pred_labels
})

# Hiển thị 20 dự đoán đầu tiên
print(results.head(20))
# Đánh giá mô hình
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

       Actual  Predicted
0   delivered  delivered
1   delivered  delivered
2   delivered  delivered
3   delivered  delivered
4   delivered  delivered
5   delivered  delivered
6   delivered  delivered
7   delivered  delivered
8   delivered  delivered
9   delivered  delivered
10  delivered  delivered
11  delivered  delivered
12  delivered  delivered
13  delivered  delivered
14  delivered  delivered
15  delivered  delivered
16  delivered  delivered
17  delivered  delivered
18  delivered  delivered
19  delivered  delivered
[[    1     0     0     0     0     0     0]
 [    1    38   110     2     2     1     0]
 [    1    36 33842    13    23    63     1]
 [    1     1    93    14     2     2     0]
 [    0     0    66     1    25     3     0]
 [    0     3   289     3     3    39     0]
 [    0     0     4     0     0     0     0]]
              precision    recall  f1-score   support

           0       0.25      1.00      0.40         1
           1       0.49      0.25      0.33       

* dự đoán về tình trạng đơn hàng

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
df=pd.read_csv('data.csv')

df = df[['price', 'freight_value', 'review_score', 'product_category_name', 'payment_type']]
df['product_category_name'] = df['product_category_name'].astype('category').cat.codes
df['payment_type'] = df['payment_type'].astype('category').cat.codes
X = df.drop('review_score', axis=1)
y = df['review_score']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Khởi tạo và huấn luyện mô hình hồi quy tuyến tính
model = LinearRegression()
model.fit(X_train, y_train)

# Dự đoán trên dữ liệu kiểm tra
y_pred = model.predict(X_test)
# đánh giá mô hình 
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

# Hiển thị hệ số hồi quy và giao cắt
print(f'Coefficients: {model.coef_}')
print(f'Intercept: {model.intercept_}')


Mean Squared Error: 1.8981249242945029
Coefficients: [ 9.54689092e-05 -3.71440145e-03 -7.73834616e-04 -1.22963935e-03]
Intercept: 4.1232466037065905


In [24]:
#dự đoán cho đơn hành mới 
# Ví dụ dữ liệu mới để dự đoán
new_data = pd.DataFrame({
    'price': [50.0],
    'freight_value': [10.0],
    'product_category_name': [0],  # mã hóa danh mục sản phẩm
    'payment_type': [1]             # mã hóa loại thanh toán
})

# Dự đoán điểm đánh giá
new_predictions = model.predict(new_data)
print(f'Predicted Review Score: {new_predictions[0]}')

Predicted Review Score: 4.08964639530173


* dự đoán đánh giá của đơn hàng

In [25]:
import pandas as pd

# Đọc dữ liệu từ file CSV
df = pd.read_csv('data.csv')

# Chuyển đổi cột ngày tháng thành định dạng datetime
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_purchase_date_dmy'] = df['order_purchase_timestamp'].dt.strftime('%d/%m/%Y')
df['total_revenue'] = df['price'] * df['freight_value']
df['order_date'] = df['order_purchase_timestamp'].dt.date

# Nhóm theo ngày và tính tổng doanh thu
daily_revenue = df.groupby('order_date')['total_revenue'].sum().reset_index()

# Chuyển đổi ngày thành định dạng 'd/m/y'
daily_revenue['order_date_dmy'] = daily_revenue['order_date'].apply(lambda x: x.strftime('%d/%m/%Y'))
daily_revenue = daily_revenue.sort_values(by='order_date')
# Xem kết quả
print(daily_revenue[['order_date', 'order_date_dmy', 'total_revenue']].head(20))

    order_date order_date_dmy  total_revenue
0   2016-09-04     04/09/2016      2308.4263
1   2016-09-05     05/09/2016       925.8200
2   2016-10-02     02/10/2016       934.0000
3   2016-10-03     03/10/2016      8338.5680
4   2016-10-04     04/10/2016    258034.0830
5   2016-10-05     05/10/2016    318597.3280
6   2016-10-06     06/10/2016    295011.0511
7   2016-10-07     07/10/2016    151240.2484
8   2016-10-08     08/10/2016    243594.5841
9   2016-10-09     09/10/2016    100985.1789
10  2016-10-10     10/10/2016     89981.8491
11  2016-12-23     23/12/2016        95.0480
12  2017-01-05     05/01/2017      4957.2050
13  2017-01-06     06/01/2017    101860.9235
14  2017-01-07     07/01/2017     29266.1270
15  2017-01-08     08/01/2017     12220.5091
16  2017-01-09     09/01/2017     12624.9764
17  2017-01-10     10/01/2017     37591.4163
18  2017-01-11     11/01/2017     82776.9503
19  2017-01-12     12/01/2017     48332.7629


In [26]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
daily_revenue['order_date_dmy'] = pd.to_datetime(daily_revenue['order_date'])
daily_revenue['date_num'] = (daily_revenue['order_date_dmy'] - daily_revenue['order_date_dmy'].min()).dt.days

# Tách dữ liệu thành dữ liệu huấn luyện và kiểm tra
X = daily_revenue[['date_num']]
y = daily_revenue['total_revenue']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Khởi tạo và huấn luyện mô hình hồi quy tuyến tính
model = LinearRegression()
model.fit(X_train, y_train)

# Dự đoán trên dữ liệu kiểm tra
y_pred = model.predict(X_test)

# Đánh giá mô hình
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(r2)

0.4173429392446534


In [28]:
import datetime
new_dates = pd.DataFrame({
    'order_date_dmy': [datetime.date(2018, 9, 4), datetime.date(2018, 9, 4)]
})
new_dates['order_date_dmy'] = pd.to_datetime(new_dates['order_date_dmy'])
new_dates['date_num'] = (new_dates['order_date_dmy'] - daily_revenue['order_date_dmy'].min()).dt.days

# Dự đoán doanh thu
new_revenues = model.predict(new_dates[['date_num']])
new_dates['predicted_revenue'] = new_revenues
print(new_dates[['order_date_dmy', 'predicted_revenue']])

  order_date_dmy  predicted_revenue
0     2018-09-04       1.176263e+06
1     2018-09-04       1.176263e+06


* dự đoán doanh thu

In [29]:
import pandas as pd
df=pd.read_csv('dataset/olist_order_reviews_dataset.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64 
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
